code_to_name = {
    'AF': 'Afghanistan',
    'AL': 'Albania',
    'AG': 'Algeria',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AS': 'Australia',
    'BH': 'Belize"',
    'BY': 'Burundi',
    'BE': 'Belgium',
    'BO': 'Belarus',
    'BA': 'Bahrain',
    'BR': 'Brazil',
    'BG': 'Bangladesh',
    'IT': 'Italy',
    'IN': 'India',
    'IS': 'Israel',
    'CH': 'China',
    'PL': 'Poland',
    'ID': 'Indonesia',
    'NI': 'Nigeria',
    'GR': 'Greece',
    'CA': 'Canada',
    'RS': 'Russia',
    'FR': 'France',
    'MX': 'Mexico',
    'JM': 'Jamaica',
    'CO': 'Colombia',
    'EG': 'Egypt',
    'UG': 'Uganda',
    'CU': 'Cuba',
    'HR': 'Croatia',
    'MT': 'Malta',
    'MY': 'Malaysia',
    'US': 'United States of America',
    'NP': 'Nepal',
    'PE': 'Peru',
    'LU': 'Luxembourg',
    'PK': 'Pakistan',
    'TW': 'Taiwan',
    'TH': 'Thailand',
    'HU': 'Hungary',
    'KZ': 'Kazakhstan',
    'MK': 'Macedonia',
    'NL': 'Netherlands',
    'CM': 'Cameroon',
    'RO': 'Romania',
    'SA': 'Saudi Arabia',
    'IR': 'Iran',
    'SI': 'Slovenia',
    'GT': 'Guatemala',
    'FI': 'Finland',
    'ES': 'El Salvador',
    'CY': 'Cyprus',
    'AE': 'United Arab Emirates',
    'SG': 'Senegal',
    'GH': 'Ghana',
    'VE': 'Venezuela',
    'MD': 'Moldova',
    'PA': 'Paraguay',
    'BD': 'Bermuda',
    'SY': 'Syria',
    'EC': 'Ecuador',
    'NO': 'Norway'
}
