"""
GDELT country code to country name mapping.
This file contains a comprehensive list of GDELT country codes and their corresponding names.
"""

COUNTRY_CODES = {
    # Common country codes
    "1": "Global",
    "2": "Africa",
    "4": "Americas",
    "3": "Asia",
    "7": "Central Africa",
    "8": "Central America",
    "10": "Central Asia",
    "11": "Eastern Africa",
    "12": "Eastern Asia",
    "13": "Eastern Europe",
    "14": "Europe",
    "15": "Middle East & North Africa",
    "16": "Middle East",
    "17": "North Africa",
    "18": "North America",
    "19": "Northern Europe",
    "20": "Oceania",
    "21": "South America",
    "22": "South Asia",
    "23": "South-Eastern Asia",
    "24": "Southern Africa",
    "25": "Southern Europe",
    "26": "Western Africa",
    "27": "Western Asia",
    "28": "Western Europe",
    "39": "Balkans",
    "65": "Caribbean",
    
    # Common countries from the dataset
    # Basic country codes
    "26423": "United Kingdom",
    "13001": "United States",
    "18315": "Germany",
    "25106": "France",
    "DC001": "Washington DC",
    "40110": "Israel",
    "25307": "France",
    "25852": "Germany",
    "24213": "France",
    "12390": "Canada",
    "12220": "United States",
    "40420": "Palestine",
    "40550": "Lebanon",
    "36515": "Russia",
    "36520": "Ukraine",
    "20610": "Australia",
    "20900": "New Zealand",
    "24520": "Spain",
    "25350": "Italy",
    "19999": "Mexico",
    "23100": "India",
    "23230": "Pakistan",
    "23500": "China",
    "23800": "Japan",
    "23910": "South Korea",
    "23800": "North Korea",
    "27510": "Iran",
    "27630": "Saudi Arabia",
    "29310": "Brazil",
    "29900": "Argentina",
    "31520": "Nigeria",
    "31320": "Kenya",
    "31010": "Egypt",
    "31050": "South Africa",
    "31570": "Somalia",
    "32100": "Turkey",
    "32330": "Greece",
    "33300": "Norway",
    "33510": "Sweden",
    "33400": "Finland",
    "33700": "Denmark",
    "35000": "Belgium",
    "35200": "Netherlands",
    "35400": "Switzerland",
    "35600": "Poland",
    "36000": "Austria",
    "36200": "Hungary",
    "37000": "Ireland",
    "38900": "Portugal",
    "39100": "Czech Republic",
    "39500": "Slovakia",
    "41200": "Syria",
    "41400": "Jordan",
    "41600": "Iraq",
    "43100": "Afghanistan",
    "45000": "Myanmar",
    "45100": "Thailand",
    "45200": "Vietnam",
    "45300": "Cambodia",
    "45500": "Indonesia",
    "45600": "Malaysia",
    "45700": "Philippines",
    "45800": "Singapore",
    "45900": "Taiwan",
    
    # Additional codes found in the dataset
    "19588": "Scotland",
    "25068": "Vatican City",
    "40112": "Gaza Strip",
    "22963": "India (Kashmir)",
    "17198": "Northern Ireland",
    "13072": "United States (California)",
    "27516": "Syria",
    "12755": "United States (Texas)",
    "191300": "European Union",
    "24250": "Italy (Rome)",
    "24272": "Spain (Barcelona)",
    "77363": "African Union",
    "111381": "UN Security Council",
    "26507": "Wales",
    "190655": "NATO",
    "40108": "Israel (Jerusalem)",
    "28575": "Germany (Berlin)",
    "13260": "United States (New York)",
    "17911": "Ireland (Dublin)",
    
    # More codes from the dataset
    "26319": "England",
    "18965": "Sweden (Stockholm)",
    "25835": "Italy (Milan)",
    "CO031": "Colorado",
    "23034": "India (New Delhi)",
    "5840": "United Nations",
    "191172": "European Commission",
    "13054": "United States (Florida)",
    "40137": "Lebanon (Beirut)",
    "191100": "European Parliament",
    "191205": "European Central Bank",
    "13325": "United States (Washington State)",
    "26324": "England (Manchester)",
    "5096": "International Criminal Court",
    "191416": "G7",
    "18585": "Norway (Oslo)",
    "17660": "Denmark (Copenhagen)",
    "22908": "Pakistan (Islamabad)",
    "40114": "West Bank",
    "25851": "Italy (Vatican)",
    "190720": "World Health Organization",
    "24789": "Spain (Madrid)",
    "OH081": "Ohio",
    "25415": "Greece (Athens)",
    "22726": "Bangladesh",
    "CA037": "California",
    "70116": "International Monetary Fund",
    "24254": "Italy (Naples)",
    "22911": "Pakistan (Karachi)",
    "24210": "Spain (Catalonia)",
    "25036": "Portugal (Lisbon)",
    "IN083": "Indiana",
    "17644": "Ireland (Belfast)",
    "191392": "G20",
    "IL031": "Illinois",
    "47629": "Saudi Arabia (Riyadh)",
    "17683": "Iceland",
    "40102": "Israel (Tel Aviv)",
    "13218": "United States (Massachusetts)",
    "154637": "Commonwealth of Nations",
    "13148": "United States (Georgia)",
    "19796": "United Kingdom (Scotland)",
    "GA305": "Georgia (Atlanta)",
    "191295": "OECD",
    "24267": "Spain (Seville)",
    "74067": "World Bank",
    "40098": "Israel (Haifa)",
    "17564": "Denmark (Aarhus)",
    "40124": "Palestine (Ramallah)",
    "NC183": "North Carolina",
    "190646": "World Trade Organization",
    "40158": "Syria (Damascus)",
    "5850": "UNESCO",
    "MA025": "Massachusetts",
    "190990": "Interpol",
    "40132": "Jordan (Amman)",
    "36340": "Belarus",
    "22749": "Nepal",
    "TX113": "Texas",
    "40127": "Iraq (Baghdad)",
    "24984": "Portugal (Porto)",
    "13243": "United States (Michigan)",
    "28554": "Germany (Munich)",
    "191147": "Council of Europe",
    "154724": "Arab League",
    "22903": "Pakistan (Lahore)",
    "13320": "United States (Washington)",
    "70159": "International Atomic Energy Agency",
    "OH061": "Ohio (Cleveland)",
    "17914": "Ireland (Cork)",
    "65350": "Jamaica",
    "40173": "Yemen",
    "23118": "Bangladesh (Dhaka)",
    "22392": "Sri Lanka",
    "16532": "Estonia",
    "16538": "Latvia",
    "27897": "Turkey (Istanbul)",
    "13033": "United States (Connecticut)",
    "13151": "United States (Georgia)",
    "41107": "Egypt (Cairo)",
    "19310": "Norway (Bergen)",
    "34163": "Netherlands (Amsterdam)",
    "25844": "Italy (Florence)",
    "24233": "Spain (Valencia)",
    "23119": "Bangladesh (Chittagong)",
    "34930": "Belgium (Brussels)",
    "25830": "Italy (Turin)",
    "37316": "Russia (Moscow)",
    "24238": "Spain (Zaragoza)",
    "IN055": "Indiana (Indianapolis)",
    "31933": "South Africa (Cape Town)",
    
    # Common city codes
    "USNYC": "New York",
    "USWDC": "Washington DC",
    "USCHI": "Chicago",
    "USLAX": "Los Angeles",
    "GBLON": "London",
    "FXPAR": "Paris",
    "RSMOS": "Moscow",
    "CHBEI": "Beijing",
    "JPTYO": "Tokyo",
    "INNDL": "New Delhi",
    "BRRIO": "Rio de Janeiro",
    "ARBUS": "Buenos Aires",
    "TZPDI": "Cape Town",
    "AUSYD": "Sydney",
    "TRIST": "Istanbul",
    "CATOR": "Toronto",
    "MXMEX": "Mexico City",
    "EGCAI": "Cairo",
    "DEBER": "Berlin",
    "ITROM": "Rome",
    "NLAMS": "Amsterdam",
    "RUDRM": "Damascus",
    "IRBAG": "Baghdad",
    "AFDOH": "Doha",
    "SGRBD": "Singapore",
    "KOREO": "Seoul",
    "SAFRI": "Riyadh",
    "LRLON": "London",
    
    # US States
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

# Function to load all country codes from a text file (if available)
def load_additional_codes():
    """
    Try to load additional country codes from a text file if it exists.
    Format should be: code|name (one per line)
    """
    try:
        import os
        filepath = os.path.join(os.path.dirname(__file__), 'additional_country_codes.txt')
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                for line in f:
                    if '|' in line:
                        code, name = line.strip().split('|', 1)
                        COUNTRY_CODES[code.strip()] = name.strip()
    except Exception as e:
        print(f"Error loading additional country codes: {e}")

# Load additional codes if available


def get_country_name(code):
    """
    Get country name from GDELT country code.
    
    Args:
        code (str): GDELT country code
            
    Returns:
        str: Country name or original code if not found
    """
    return COUNTRY_CODES.get(str(code), code) 